# see https://github.com/bbatsov/ruby-style-guide#percent-q-shorthand

AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
  DisplayCopNames: true

Metrics/LineLength:
  Max: 500

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 320

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 50

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Enabled: true
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 6

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/HashSyntax:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/RegexpLiteral:
  Enabled: false

Style/Alias:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/MethodMissing:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
